### ISSUE TITLE
Questions about the paper, need your answers.

### ISSUE THREAD

**Issue by WWork1** [yuhao-nie/SkyGPT#1]
Thank you for your great work. I currently have a question that I would like you to answer. Does sunlight have an impact on sky image predictions? Will this lead to models skewing PV predictions towards sun position or light intensity rather than cloud movement?

**Comment by yuhao-nie** [comment]
Thanks for your question. I am not quite sure what you mean by "does sunlight have impact on sky image prediction" or you actually mean would sunlight have impact on PV output prediction. Our model can capture the movement of both the sun and the clouds. Yes, the sunlight (i.e., intensity and position) will have impact on the PV output prediction and these behaviors can be well modeled by either clear sky models based on physics or learned by deep learning models based on sky images. The difficulties for current solar forecasting research (especially short-term forecasting) really are the rapidly changing cloud dynamics. You can take a look at our repo [here](https://github.com/yuhao-nie/Stanford-solar-forecasting-dataset). PV output on sunny days can be predicted almost perfectly by the model, while cloudy days obviously have much larger errors.

**Comment by WWork1** [comment]
Thank you for your answer, your answer solved my confusion.
